Repository swm-standard/phote-server, pull requests merged in 2024-07, with the labels that each got.

#4 Feat: Sentry 세팅
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/PhoteApplication.kt
Labels: 🙌🏻 Setting, ✨ Feature

#2 Init : 엔티티 (DB 테이블) 작성
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/entity/Member.kt
  src/main/kotlin/com/swm_standard/phote/entity/Provider.kt
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/entity/QuestionSet.kt
  src/main/kotlin/com/swm_standard/phote/entity/Tag.kt
  src/main/kotlin/com/swm_standard/phote/entity/WorkBook.kt
Labels: 🙌🏻 Setting

#11 Feat: google login
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/common/authority/JwtAuthenticationFilter.kt
  src/main/kotlin/com/swm_standard/phote/common/authority/JwtTokenProvider.kt
  src/main/kotlin/com/swm_standard/phote/common/authority/SecurityConfig.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/InvalidInputException.kt
  src/main/kotlin/com/swm_standard/phote/common/responsebody/BaseResponse.kt
  src/main/kotlin/com/swm_standard/phote/common/responsebody/EnumStatus.kt
  src/main/kotlin/com/swm_standard/phote/controller/AuthController.kt
  src/main/kotlin/com/swm_standard/phote/dto/AuthDtos.kt
  src/main/kotlin/com/swm_standard/phote/service/AuthService.kt
Labels: ✨ Feature

#15 Feat: 문제집 생성
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/common/authority/JwtAuthenticationFilter.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Member.kt
  src/main/kotlin/com/swm_standard/phote/entity/WorkBook.kt
  src/main/kotlin/com/swm_standard/phote/repository/MemberRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/WorkbookRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
Labels: ✨ Feature

#22 Fix: 이미 삭제된 문제집을 다시 삭제시키는 오류
  src/main/kotlin/com/swm_standard/phote/PhoteApplication.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/AlreadyDeletedException.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
Labels: 🛠️ Fix

#21 문제집 정보 상세 읽기 (Seyeon/swm 41)
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Member.kt
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/entity/QuestionSet.kt
  src/main/kotlin/com/swm_standard/phote/entity/Workbook.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionSetRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
  src/test/kotlin/com/swm_standard/phote/service/WorkbookServiceTest.kt
Labels: ✨ Feature

#25 !HOTFIX: CustomExceptionHandler 미사용 ResultCode 제거 (Seyeon/swm-48)
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
Labels: 🛠️ Fix

#23 Feat: memberIdResolver구현
  .gitignore
  src/main/kotlin/com/swm_standard/phote/common/authority/JwtTokenProvider.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/BadRequestException.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/swm_standard/phote/common/resolver/WebMvcConfig.kt
  src/main/kotlin/com/swm_standard/phote/common/resolver/memberId/MemberId.kt
  src/main/kotlin/com/swm_standard/phote/common/resolver/memberId/MemberIdResolver.kt
Labels: ✨ Feature, ☘️ surin

#28 !HOTFIX: errorcode변경
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
Labels: 🛠️ Fix, ☘️ surin

#29 Fix: JPA 엔티티 PK 수정
  src/main/kotlin/com/swm_standard/phote/entity/Member.kt
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/entity/Workbook.kt
Labels: 🛠️ Fix

#30 Fix: Question의 options 필드 json으로 변경
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
Labels: 🛠️ Fix

#32 Feat: RDS 용 secret manager 설정
  build.gradle.kts
Labels: ✨ Feature

#13 Feat: readQuestionDetail
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/NotFoundException.kt
  src/main/kotlin/com/swm_standard/phote/common/responsebody/EnumStatus.kt
  src/main/kotlin/com/swm_standard/phote/controller/QuestionController.kt
  src/main/kotlin/com/swm_standard/phote/dto/response/ReadQuestionDetailResponseDto.kt
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/repository/MemberRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionSetRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/WorkbookRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: ✨ Feature, ☘️ surin

#45 Fix: @MemberId resolver 타입 버그 수정
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/common/authority/JwtTokenProvider.kt
  src/main/kotlin/com/swm_standard/phote/common/resolver/memberId/MemberIdResolver.kt
  src/main/kotlin/com/swm_standard/phote/controller/QuestionController.kt
  src/main/kotlin/com/swm_standard/phote/dto/response/ReadQuestionDetailResponseDto.kt
Labels: 🛠️ Fix, ☘️ surin

#46 FIX: readQuestionDetail 데이터 필드가 없을 때 안불러지는 오류
  src/main/kotlin/com/swm_standard/phote/dto/response/ReadQuestionDetailResponseDto.kt
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: 🛠️ Fix, ☘️ surin

#34 Feat: DeleteQuestion
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/swm_standard/phote/controller/QuestionController.kt
  src/main/kotlin/com/swm_standard/phote/dto/QuestionDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: ✨ Feature, ☘️ surin

#47 Fix: readWorkbookDetail 관련 오류 (exception 처리, 기삭제된 문제집)
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
  src/main/kotlin/com/swm_standard/phote/dto/QuestionSetDtos.kt
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/entity/QuestionSet.kt
  src/main/kotlin/com/swm_standard/phote/entity/Workbook.kt
  src/main/kotlin/com/swm_standard/phote/repository/WorkbookRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
  src/test/kotlin/com/swm_standard/phote/entity/WorkbookTest.kt
Labels: 🛠️ Fix

#49 Fix: deleteQuestion시 QuestionSet entity 업데이트
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionSetRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: 🛠️ Fix, ☘️ surin

#53 Fix: exception에서 fieldName표시하도록 Refactor
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: 🛠️ Fix, 🔨 Refactor, ☘️ surin

#51 Fix: Workbook 삭제 시 연관된 QuestionSet 도 삭제
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/QuestionSet.kt
  src/main/kotlin/com/swm_standard/phote/entity/Workbook.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
Labels: 🛠️ Fix, 🔨 Refactor, 🫧 seyeon

#55 Fix: deleteQuestion 로직 Refactor + Question 엔티티 수정
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: 🛠️ Fix, 🔨 Refactor, ☘️ surin

#59 Feat: readWorkbookList (Seyeon/swm 57)
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Workbook.kt
  src/main/kotlin/com/swm_standard/phote/repository/WorkbookRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
  src/test/kotlin/com/swm_standard/phote/entity/WorkbookTest.kt
Labels: ✨ Feature, 🫧 seyeon

#63 Fix: question의 options 필드 JsonNode로 변경
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/entity/Tag.kt
Labels: 🛠️ Fix, 🫧 seyeon

#64 Fix: readQuestionDetail api response에 tag추가 & options타입 변경에 따른 조회 로직 수정
  src/main/kotlin/com/swm_standard/phote/dto/QuestionDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/repository/TagRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: 🛠️ Fix, ☘️ surin

#66 Feat: addQuestionstoWorkbook
  src/main/kotlin/com/swm_standard/phote/common/exception/AlreadyDeletedException.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/QuestionSet.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionSetRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
Labels: ✨ Feature, 🫧 seyeon

#60 Feat: CreateQuestion 구현
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/swm_standard/phote/controller/QuestionController.kt
  src/main/kotlin/com/swm_standard/phote/dto/QuestionDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/entity/Tag.kt
  src/main/kotlin/com/swm_standard/phote/external/aws/S3Config.kt
  src/main/kotlin/com/swm_standard/phote/external/aws/S3Service.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: ✨ Feature, ☘️ surin

#67 [Feat] kakao login
  src/main/kotlin/com/swm_standard/phote/common/module/NicknameGenerator.kt
  src/main/kotlin/com/swm_standard/phote/controller/AuthController.kt
  src/main/kotlin/com/swm_standard/phote/dto/AuthDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Member.kt
  src/main/kotlin/com/swm_standard/phote/service/GoogleAuthService.kt
  src/main/kotlin/com/swm_standard/phote/service/KaKaoAuthService.kt
Labels: ✨ Feature, ☘️ surin

#68 Feat: deleteQuestionInWorkbook
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Workbook.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
  src/test/kotlin/com/swm_standard/phote/entity/WorkbookTest.kt
Labels: ✨ Feature, 🫧 seyeon

#72 Fix: deleteQuestion시 workbook의 quantity도 감소
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: 🛠️ Fix, ☘️ surin

#74 Fix: 문제집 상세에 문제 개수 추가 / 문제 변동 시 문제집 수정일 변경 (Seyeon/swm 79)
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Workbook.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
  src/test/kotlin/com/swm_standard/phote/entity/WorkbookTest.kt
Labels: 🛠️ Fix, 🫧 seyeon

#70 Feat: SearchQuestions
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/controller/QuestionController.kt
  src/main/kotlin/com/swm_standard/phote/external/querydsl/QueryDslConfig.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionCustomRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionCustomRepositoryImpl.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: ✨ Feature, ☘️ surin

#76 Feat: updateQuestionSequence (Seyeon/swm 75)
  src/main/kotlin/com/swm_standard/phote/common/exception/AlreadyExistedException.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
  src/main/kotlin/com/swm_standard/phote/dto/QuestionSetDtos.kt
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/QuestionSet.kt
  src/main/kotlin/com/swm_standard/phote/entity/Workbook.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionSetCustomRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionSetCustomRepositoryImpl.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionSetRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
  src/test/kotlin/com/swm_standard/phote/entity/QuestionSetTest.kt
Labels: ✨ Feature, 🫧 seyeon

#81 Infra: ec2 배포
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  src/main/kotlin/com/swm_standard/phote/common/authority/JwtTokenProvider.kt
Labels: 🌏 Infra, 🫧 seyeon

#85 Feat: readQuestionsInWorkbook
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
  src/main/kotlin/com/swm_standard/phote/dto/QuestionDtos.kt
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Category.kt
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/entity/QuestionSet.kt
  src/main/kotlin/com/swm_standard/phote/entity/Tag.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionSetRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
Labels: ✨ Feature, 🫧 seyeon

#88 Fix: 구글 첫 로그인 시 랜덤 닉네임, 이미지 부여
  src/main/kotlin/com/swm_standard/phote/common/module/ProfileImageGenerator.kt
  src/main/kotlin/com/swm_standard/phote/controller/AuthController.kt
  src/main/kotlin/com/swm_standard/phote/dto/AuthDtos.kt
  src/main/kotlin/com/swm_standard/phote/service/GoogleAuthService.kt
Labels: 🛠️ Fix, 🔨 Refactor, 🫧 seyeon

#91 Feat: seachQuestionsToAdd 구현
  src/main/kotlin/com/swm_standard/phote/controller/QuestionController.kt
  src/main/kotlin/com/swm_standard/phote/dto/QuestionDtos.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionCustomRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionCustomRepositoryImpl.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: ✨ Feature, ☘️ surin

#92 Fix: kakao login 초기 프로필 이미지 변경
  src/main/kotlin/com/swm_standard/phote/service/KaKaoAuthService.kt
Labels: 🛠️ Fix, ☘️ surin

#93 Fix: createQuestion api의 request에서 category NotBlank에서 NotNull로 변경
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/swm_standard/phote/dto/QuestionDtos.kt
Labels: 🛠️ Fix, ☘️ surin

#94 Feat: updateWorkbookDetail 구현
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
Labels: ✨ Feature, ☘️ surin

#96 Refactor: workbookService @DynamicUpdate 제거
  src/main/kotlin/com/swm_standard/phote/entity/Workbook.kt
Labels: 🛠️ Fix, 🫧 seyeon

#98 Refactor: dto명 통일
  src/main/kotlin/com/swm_standard/phote/common/authority/JwtTokenProvider.kt
  src/main/kotlin/com/swm_standard/phote/controller/AuthController.kt
  src/main/kotlin/com/swm_standard/phote/controller/QuestionController.kt
  src/main/kotlin/com/swm_standard/phote/dto/AuthDtos.kt
  src/main/kotlin/com/swm_standard/phote/dto/QuestionDtos.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionCustomRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionCustomRepositoryImpl.kt
  src/main/kotlin/com/swm_standard/phote/service/GoogleAuthService.kt
  src/main/kotlin/com/swm_standard/phote/service/KaKaoAuthService.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: 🔨 Refactor, ☘️ surin

#99 Feat: updateQuestionSequence 에서 questionSetId를 사용하도록 변경
  src/main/kotlin/com/swm_standard/phote/entity/QuestionSet.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionSetRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
Labels: ✨ Feature, 🫧 seyeon

#100 Feat: matchEmojiByTitle
  src/main/kotlin/com/swm_standard/phote/common/authority/JwtTokenProvider.kt
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Workbook.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
Labels: ✨ Feature, 🫧 seyeon

#102 Fix: cors 관련 허용 처리
  src/main/kotlin/com/swm_standard/phote/common/resolver/WebMvcConfig.kt
Labels: 🛠️ Fix

#103 Fix: cors 관련 허용 처리 (SecurityConfig에도)
  src/main/kotlin/com/swm_standard/phote/common/authority/SecurityConfig.kt
Labels: 🛠️ Fix, 🫧 seyeon

#106 Setting: KtLint 및 pre-commit 세팅
  .editorconfig
  .github/ISSUE_TEMPLATE/issue--✅-feature.md
  .github/ISSUE_TEMPLATE/issue--🐞-bug.md
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  src/main/kotlin/com/swm_standard/phote/PhoteApplication.kt
  src/main/kotlin/com/swm_standard/phote/common/authority/JwtAuthenticationFilter.kt
  src/main/kotlin/com/swm_standard/phote/common/authority/JwtTokenProvider.kt
  src/main/kotlin/com/swm_standard/phote/common/authority/SecurityConfig.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/AlreadyExistedException.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/BadRequestException.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/InvalidInputException.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/NotFoundException.kt
  src/main/kotlin/com/swm_standard/phote/common/module/NicknameGenerator.kt
  src/main/kotlin/com/swm_standard/phote/common/module/ProfileImageGenerator.kt
  src/main/kotlin/com/swm_standard/phote/common/resolver/WebMvcConfig.kt
  src/main/kotlin/com/swm_standard/phote/common/resolver/memberId/MemberId.kt
  src/main/kotlin/com/swm_standard/phote/common/resolver/memberId/MemberIdResolver.kt
  src/main/kotlin/com/swm_standard/phote/common/responsebody/BaseResponse.kt
  src/main/kotlin/com/swm_standard/phote/common/responsebody/EnumStatus.kt
  src/main/kotlin/com/swm_standard/phote/controller/AuthController.kt
  src/main/kotlin/com/swm_standard/phote/controller/QuestionController.kt
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
  src/main/kotlin/com/swm_standard/phote/dto/AuthDtos.kt
  src/main/kotlin/com/swm_standard/phote/dto/QuestionDtos.kt
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Category.kt
  src/main/kotlin/com/swm_standard/phote/entity/Member.kt
  src/main/kotlin/com/swm_standard/phote/entity/Provider.kt
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/entity/QuestionSet.kt
  src/main/kotlin/com/swm_standard/phote/entity/Workbook.kt
  src/main/kotlin/com/swm_standard/phote/external/aws/S3Config.kt
  src/main/kotlin/com/swm_standard/phote/external/aws/S3Service.kt
  src/main/kotlin/com/swm_standard/phote/external/querydsl/QueryDslConfig.kt
  src/main/kotlin/com/swm_standard/phote/repository/MemberRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionCustomRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionCustomRepositoryImpl.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionSetCustomRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionSetCustomRepositoryImpl.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionSetRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/TagRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/WorkbookRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/GoogleAuthService.kt
  src/main/kotlin/com/swm_standard/phote/service/KaKaoAuthService.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
  src/test/kotlin/com/swm_standard/phote/PhoteApplicationTests.kt
  src/test/kotlin/com/swm_standard/phote/entity/QuestionSetTest.kt
  src/test/kotlin/com/swm_standard/phote/entity/WorkbookTest.kt
Labels: 🙌🏻 Setting, 🫧 seyeon

#107 Feat: Swagger 연동
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/common/authority/SecurityConfig.kt
  src/main/kotlin/com/swm_standard/phote/controller/AuthController.kt
  src/main/kotlin/com/swm_standard/phote/controller/QuestionController.kt
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
  src/main/kotlin/com/swm_standard/phote/external/swagger/SwaggerConfig.kt
Labels: ✨ Feature, ☘️ surin

#108 Feat: transformQuestion
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/common/exception/ChatGptErrorException.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/swm_standard/phote/common/responsebody/EnumStatus.kt
  src/main/kotlin/com/swm_standard/phote/controller/AuthController.kt
  src/main/kotlin/com/swm_standard/phote/controller/QuestionController.kt
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
  src/main/kotlin/com/swm_standard/phote/dto/ChatGptDtos.kt
  src/main/kotlin/com/swm_standard/phote/dto/QuestionDtos.kt
  src/main/kotlin/com/swm_standard/phote/external/chatgpt/ChatGptConfig.kt
  src/main/kotlin/com/swm_standard/phote/external/chatgpt/Prompt.kt
  src/main/kotlin/com/swm_standard/phote/external/swagger/SwaggerConfig.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: ✨ Feature, 🫧 seyeon

#113 Feat: S3 버킷 폴더 구분
  src/main/kotlin/com/swm_standard/phote/controller/QuestionController.kt
  src/main/kotlin/com/swm_standard/phote/external/aws/S3Service.kt
Labels: ✨ Feature, 🫧 seyeon

#115 Fix: readQuestionsInWorkbook 에서 sequence 삭제
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
Labels: 🛠️ Fix, 🫧 seyeon

#117 Fix: updateWorkbookDetail dto 수정
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
Labels: 🛠️ Fix, ☘️ surin

#118 Feat: 문제 풀이 ERD
  src/main/kotlin/com/swm_standard/phote/entity/Answer.kt
  src/main/kotlin/com/swm_standard/phote/entity/Exam.kt
Labels: ✨ Feature, 🫧 seyeon

#123 Feat: CustomAuditingEntity 구현
  src/main/kotlin/com/swm_standard/phote/PhoteApplication.kt
  src/main/kotlin/com/swm_standard/phote/entity/Answer.kt
  src/main/kotlin/com/swm_standard/phote/entity/BaseTimeEntity.kt
  src/main/kotlin/com/swm_standard/phote/entity/Exam.kt
  src/main/kotlin/com/swm_standard/phote/entity/Member.kt
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/entity/QuestionSet.kt
  src/main/kotlin/com/swm_standard/phote/entity/Tag.kt
  src/main/kotlin/com/swm_standard/phote/entity/Workbook.kt
  src/main/kotlin/com/swm_standard/phote/external/chatgpt/Prompt.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionCustomRepositoryImpl.kt
Labels: ✨ Feature, 🫧 seyeon

#124 🌎 Infra: Dockerfile 세팅
  .gitignore
  Dockerfile
  build.gradle.kts
Labels: 🌏 Infra, ☘️ surin

#126 ♻️ Refactor: Question 관련 코드 리팩토링
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
  src/test/kotlin/com/swm_standard/phote/entity/QuestionRepositoryTest.kt
Labels: ✅ Test, 🔨 Refactor, ☘️ surin

#129 Test: Question 관련 테스트 코드 작성
  build.gradle.kts
  src/test/kotlin/com/swm_standard/phote/entity/QuestionRepositoryTest.kt
Labels: ✅ Test, ☘️ surin

#130 Refactor: Workbook 관련 코드 리팩토링
  src/main/kotlin/com/swm_standard/phote/entity/QuestionSet.kt
  src/main/kotlin/com/swm_standard/phote/entity/Workbook.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionSetRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
  src/test/kotlin/com/swm_standard/phote/entity/WorkbookTest.kt
Labels: ✅ Test, 🔨 Refactor, 🫧 seyeon

#138 Fix: options 반환 타입 변경
  src/main/kotlin/com/swm_standard/phote/controller/QuestionController.kt
  src/main/kotlin/com/swm_standard/phote/dto/QuestionDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionCustomRepositoryImpl.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
  src/test/kotlin/com/swm_standard/phote/entity/QuestionTest.kt
Labels: 🛠️ Fix, ☘️ surin
