Repository swm-standard/phote-server, pull requests merged in 2024-11, with the labels that each got.

#269 Fix: searchQuestions 쿼리문 distinct 제거
  src/main/kotlin/com/swm_standard/phote/repository/questionrepository/QuestionCustomRepositoryImpl.kt
Labels: 🛠️ Fix, 🫧 seyeon

#271 Feat: readAllSharedExam 응답에 workbookId 추가
  src/main/kotlin/com/swm_standard/phote/dto/ExamDtos.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
Labels: ✨ Feature, 🫧 seyeon

#272 CD: release 배포
  src/main/kotlin/com/swm_standard/phote/dto/ExamDtos.kt
  src/main/kotlin/com/swm_standard/phote/repository/questionrepository/QuestionCustomRepositoryImpl.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
Labels: ⭐️ Release
