Repository swm-standard/phote-server, pull requests merged in 2024-09, with the labels that each got.

#201 Fix: jacoco 관련 설정 추가
  build.gradle.kts
Labels: 🛠️ Fix, ☘️ surin

#203 Fix: jacoco test Report 불필요 클래스 제외
  .github/workflows/develop-ci.yml
  build.gradle.kts
Labels: 🛠️ Fix

#206 Fix: 구글 로그인 auth code 디코딩 & newrelic 관련 폴더 추가
  .github/workflows/develop-cd.yml
  Dockerfile
  newrelic/LICENSE
  newrelic/THIRD_PARTY_NOTICES.md
  newrelic/extension-example.xml
  newrelic/extension.xsd
  src/main/kotlin/com/swm_standard/phote/service/GoogleAuthService.kt
Labels: 🛠️ Fix, ✨ Feature

#207 Test: jacoco test coverage에 맞게 테스트 코드 작성
  .github/workflows/develop-ci.yml
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/common/module/Qualifier.kt
  src/main/kotlin/com/swm_standard/phote/entity/QuestionSet.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
  src/test/kotlin/com/swm_standard/phote/entity/AnswerTest.kt
  src/test/kotlin/com/swm_standard/phote/entity/ExamTest.kt
  src/test/kotlin/com/swm_standard/phote/entity/QuestionSetTest.kt
  src/test/kotlin/com/swm_standard/phote/entity/QuestionTest.kt
  src/test/kotlin/com/swm_standard/phote/entity/WorkbookTest.kt
Labels: ✅ Test

#211 Fix: swagger 숨길 파라미터 설정
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
Labels: 🛠️ Fix

#213 Feat: GitActions 와 Jacoco 연동
  .github/workflows/develop-ci.yml
Labels: ✨ Feature

#216 Fix: 트랜잭션 설정 및 fixtureMonkey 테스트 코드 전체 적용
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/entity/Workbook.kt
  src/main/kotlin/com/swm_standard/phote/service/MemberService.kt
  src/main/kotlin/com/swm_standard/phote/service/TokenService.kt
  src/test/kotlin/com/swm_standard/phote/entity/AnswerTest.kt
  src/test/kotlin/com/swm_standard/phote/entity/ExamTest.kt
  src/test/kotlin/com/swm_standard/phote/entity/QuestionSetTest.kt
  src/test/kotlin/com/swm_standard/phote/entity/QuestionTest.kt
  src/test/kotlin/com/swm_standard/phote/entity/WorkbookTest.kt
Labels: 🛠️ Fix, ✅ Test

#218 Feat: Apple login 구현
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/controller/AuthController.kt
  src/main/kotlin/com/swm_standard/phote/service/AppleAuthService.kt
Labels: ✨ Feature, ☘️ surin

#225 HOTFIX: health check 용 api 구현
  .gitignore
  src/main/kotlin/com/swm_standard/phote/common/authority/JwtAuthenticationFilter.kt
  src/main/kotlin/com/swm_standard/phote/common/authority/SecurityConfig.kt
  src/main/kotlin/com/swm_standard/phote/controller/HealthCheckController.kt
Labels: 🛠️ Fix, 🫧 seyeon

#223 Docs: README 작성
  README.md
Labels: 📃 Docs, ☘️ surin

#227 Fix: Prompt 개선
  docker-compose-dev.yml
  src/main/kotlin/com/swm_standard/phote/dto/ChatGptDtos.kt
  src/main/kotlin/com/swm_standard/phote/external/chatgpt/Prompt.kt
Labels: 🛠️ Fix, 🫧 seyeon

#228 Feat: JPA 쿼리 성능 개선
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
  src/main/kotlin/com/swm_standard/phote/repository/CustomWorkbookRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/CustomWorkbookRepositoryImpl.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionSetCustomRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionSetCustomRepositoryImpl.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionSetRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/TagRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/WorkbookRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
  src/test/kotlin/com/swm_standard/phote/entity/QuestionTest.kt
  src/test/kotlin/com/swm_standard/phote/entity/WorkbookTest.kt
Labels: ✨ Feature, 🫧 seyeon, 🧹 Chore

#232 Refactor: Custom Jpa Method QueryDSL 로 변경
  src/main/kotlin/com/swm_standard/phote/repository/CustomWorkbookRepositoryImpl.kt
  src/main/kotlin/com/swm_standard/phote/repository/examrepository/ExamCustomRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/examrepository/ExamCustomRepositoryImpl.kt
  src/main/kotlin/com/swm_standard/phote/repository/examrepository/ExamRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/questionrepository/QuestionCustomRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/questionrepository/QuestionCustomRepositoryImpl.kt
  src/main/kotlin/com/swm_standard/phote/repository/questionrepository/QuestionRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/questionsetrepository/QuestionSetCustomRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/questionsetrepository/QuestionSetCustomRepositoryImpl.kt
  src/main/kotlin/com/swm_standard/phote/repository/questionsetrepository/QuestionSetRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/workbookrepository/CustomWorkbookRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/workbookrepository/CustomWorkbookRepositoryImpl.kt
  src/main/kotlin/com/swm_standard/phote/repository/workbookrepository/WorkbookRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
  src/test/kotlin/com/swm_standard/phote/entity/QuestionRepositoryTest.kt
Labels: 🔨 Refactor, 🫧 seyeon

#236 Fix: readQuestionsInWorkbook 문제 안읽히는 버그 수정
  src/main/kotlin/com/swm_standard/phote/repository/questionsetrepository/QuestionSetCustomRepositoryImpl.kt
Labels: 🛠️ Fix, ☘️ surin
