Repository swm-standard/phote-server, pull requests merged in 2024-10, with the labels that each got.

#239 Fix: S3 jpeg 허용
  src/main/kotlin/com/swm_standard/phote/external/aws/S3Service.kt
Labels: 🛠️ Fix, ☘️ surin

#240 Feat: 공유용 시험을 위한 Entity 설계 구현
  build.gradle.kts
  document/exam.puml
  document/exam_class.puml
  src/main/kotlin/com/swm_standard/phote/entity/Answer.kt
  src/main/kotlin/com/swm_standard/phote/entity/Exam.kt
  src/main/kotlin/com/swm_standard/phote/entity/ExamResult.kt
  src/main/kotlin/com/swm_standard/phote/entity/SharedExam.kt
  src/main/kotlin/com/swm_standard/phote/repository/ExamResultRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
  src/test/kotlin/com/swm_standard/phote/entity/AnswerTest.kt
  src/test/kotlin/com/swm_standard/phote/entity/ExamResultTest.kt
  src/test/kotlin/com/swm_standard/phote/entity/ExamTest.kt
  src/test/kotlin/com/swm_standard/phote/entity/WorkbookTest.kt
Labels: ✨ Feature, 🔨 Refactor, 📃 Docs, 🫧 seyeon

#242 Fix: cd 빌드 시 ktLintCheck 태스크 삭제
  .github/workflows/develop-cd.yml
Labels: 🛠️ Fix

#244 Feat: createSharedExam
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/controller/ExamController.kt
  src/main/kotlin/com/swm_standard/phote/dto/ExamDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Answer.kt
  src/main/kotlin/com/swm_standard/phote/entity/Exam.kt
  src/main/kotlin/com/swm_standard/phote/entity/SharedExam.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
  src/test/kotlin/com/swm_standard/phote/entity/AnswerTest.kt
  src/test/kotlin/com/swm_standard/phote/entity/ExamTest.kt
Labels: ✨ Feature, ✅ Test, 🫧 seyeon

#245 Feat: readExamResults 구현
  src/main/kotlin/com/swm_standard/phote/controller/ExamController.kt
  src/main/kotlin/com/swm_standard/phote/dto/ExamDtos.kt
  src/main/kotlin/com/swm_standard/phote/repository/ExamResultRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
Labels: ✨ Feature, ☘️ surin

#246 Feat: regradeExam 구현
  src/main/kotlin/com/swm_standard/phote/controller/ExamController.kt
  src/main/kotlin/com/swm_standard/phote/dto/ExamDtos.kt
  src/main/kotlin/com/swm_standard/phote/repository/AnswerRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/ExamResultRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
Labels: ✨ Feature, ☘️ surin

#247 Feat: gradeExam 공유용 시험도 함께 사용할 수 있도록 구현
  src/main/kotlin/com/swm_standard/phote/controller/AuthController.kt
  src/main/kotlin/com/swm_standard/phote/controller/ExamController.kt
  src/main/kotlin/com/swm_standard/phote/dto/AuthDtos.kt
  src/main/kotlin/com/swm_standard/phote/dto/ExamDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Exam.kt
  src/main/kotlin/com/swm_standard/phote/entity/ExamResult.kt
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/entity/SharedExam.kt
  src/main/kotlin/com/swm_standard/phote/repository/questionrepository/QuestionCustomRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/questionrepository/QuestionRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/AppleAuthService.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
  src/main/kotlin/com/swm_standard/phote/service/GoogleAuthService.kt
  src/main/kotlin/com/swm_standard/phote/service/KaKaoAuthService.kt
  src/test/kotlin/com/swm_standard/phote/entity/ExamTest.kt
Labels: ✨ Feature, 🫧 seyeon, 🧹 Chore

#249 Feat: 임시 자체 로그인 구현
  src/main/kotlin/com/swm_standard/phote/controller/AuthController.kt
  src/main/kotlin/com/swm_standard/phote/dto/AuthDtos.kt
  src/main/kotlin/com/swm_standard/phote/service/NativeAuthService.kt
Labels: ✨ Feature, 🫧 seyeon

#251 Feat: production 용 cd workflow 구현
  .github/workflows/production-cd.yml
Labels: ✨ Feature, 🌏 Infra, 🫧 seyeon

#253 Feat: ReadExamResultDetail 구현
  src/main/kotlin/com/swm_standard/phote/controller/ExamController.kt
  src/main/kotlin/com/swm_standard/phote/dto/ExamDtos.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
Labels: ✨ Feature, ☘️ surin

#255 Feat: readAllSharedExams
  src/main/kotlin/com/swm_standard/phote/controller/ExamController.kt
  src/main/kotlin/com/swm_standard/phote/dto/ExamDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Exam.kt
  src/main/kotlin/com/swm_standard/phote/entity/ExamStatus.kt
  src/main/kotlin/com/swm_standard/phote/entity/ParticipationType.kt
  src/main/kotlin/com/swm_standard/phote/repository/ExamResultRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/SharedExamRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
Labels: ✨ Feature, 🫧 seyeon

#257 Feat: readSharedExamInfo 구현
  src/main/kotlin/com/swm_standard/phote/controller/ExamController.kt
  src/main/kotlin/com/swm_standard/phote/dto/ExamDtos.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
Labels: ✨ Feature, ☘️ surin

#259 Feat: Nginx Blue/Green 무중단 배포 구현
  .github/workflows/develop-cd.yml
  .github/workflows/production-cd.yml
  docker-compose.yml
Labels: ✨ Feature, 🌏 Infra, 🫧 seyeon

#262 Fix: readExamHistoryList 본인 시험만 조회하도록 수정
  src/main/kotlin/com/swm_standard/phote/controller/ExamController.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
Labels: 🛠️ Fix, ☘️ surin

#263 Refactor: 코루틴 비동기 리팩토링
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: 🔨 Refactor, ☘️ surin

#264 CD: release 배포
  src/main/kotlin/com/swm_standard/phote/controller/ExamController.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: ⭐️ Release

#267 Feat: readExamHistoryList (시험 결과 목록 조회) 조회 성능 개선
  src/main/kotlin/com/swm_standard/phote/entity/ExamResult.kt
  src/main/kotlin/com/swm_standard/phote/repository/examresultrepository/CustomExamResultRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/examresultrepository/CustomExamResultRepositoryImpl.kt
  src/main/kotlin/com/swm_standard/phote/repository/examresultrepository/ExamResultRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
  src/test/kotlin/com/swm_standard/phote/entity/ExamResultTest.kt
Labels: ✨ Feature, 🫧 seyeon
