Repository swm-standard/phote-server, pull requests merged in 2024-08, with the labels that each got.

#141 Chore: 필요없는 null 대입 삭제
  src/main/kotlin/com/swm_standard/phote/dto/QuestionDtos.kt
Labels: ☘️ surin, 🧹 Chore

#139 Feat: ReadExamHistoryDetail 구현
  src/main/kotlin/com/swm_standard/phote/controller/ExamController.kt
  src/main/kotlin/com/swm_standard/phote/dto/ExamDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Answer.kt
  src/main/kotlin/com/swm_standard/phote/entity/Exam.kt
  src/main/kotlin/com/swm_standard/phote/repository/ExamRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
Labels: ✨ Feature, ☘️ surin

#142 Feat: readExamHistoryList 구현
  src/main/kotlin/com/swm_standard/phote/controller/ExamController.kt
  src/main/kotlin/com/swm_standard/phote/dto/ExamDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Exam.kt
  src/main/kotlin/com/swm_standard/phote/repository/ExamRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
  src/test/kotlin/com/swm_standard/phote/entity/ExamTest.kt
Labels: ✨ Feature, ☘️ surin

#143 GitAction test-automation.yml 작성
  .github/workflows/develop-ci.yml
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
Labels: 🌏 Infra, 🫧 seyeon

#144 Feat: gradeExam
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/controller/ExamController.kt
  src/main/kotlin/com/swm_standard/phote/dto/ChatGptDtos.kt
  src/main/kotlin/com/swm_standard/phote/dto/ExamDtos.kt
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Answer.kt
  src/main/kotlin/com/swm_standard/phote/entity/Exam.kt
  src/main/kotlin/com/swm_standard/phote/external/chatgpt/Prompt.kt
  src/main/kotlin/com/swm_standard/phote/repository/AnswerRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/ExamCustomRepository.kt
  src/main/kotlin/com/swm_standard/phote/repository/ExamCustomRepositoryImpl.kt
  src/main/kotlin/com/swm_standard/phote/repository/ExamRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
  src/test/kotlin/com/swm_standard/phote/entity/AnswerTest.kt
  src/test/kotlin/com/swm_standard/phote/entity/ExamTest.kt
  src/test/kotlin/com/swm_standard/phote/entity/WorkbookTest.kt
Labels: ✨ Feature, ✅ Test, 🔨 Refactor, 🫧 seyeon

#150 Fix: allowedHeaders 추가
  src/main/kotlin/com/swm_standard/phote/common/resolver/WebMvcConfig.kt
Labels: 🛠️ Fix, ☘️ surin

#151 Infra: CD(develop)파일 세팅
  .github/workflows/develop-cd.yml
Labels: 🌏 Infra, ☘️ surin

#154 Fix: CD파일 Port 정보 추가
  .github/workflows/develop-cd.yml
Labels: 🌏 Infra, ☘️ surin

#156 Fix: key -> password변경
  .github/workflows/develop-cd.yml
Labels: 🛠️ Fix, ☘️ surin

#160 Fix: cd파일 괄호 제거
  .github/workflows/develop-cd.yml
Labels: 🛠️ Fix, ☘️ surin

#147 Feat: transformQuestion 그림 변환 구현
  src/main/kotlin/com/swm_standard/phote/controller/QuestionController.kt
  src/main/kotlin/com/swm_standard/phote/dto/QuestionDtos.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: ✨ Feature, ☘️ surin

#161 Feat: 사용자 refreshToken
  docker-compose-dev.yml
  document/refreshToken sequence.puml
  src/main/kotlin/com/swm_standard/phote/common/authority/JwtAuthenticationFilter.kt
  src/main/kotlin/com/swm_standard/phote/common/authority/JwtTokenProvider.kt
  src/main/kotlin/com/swm_standard/phote/common/authority/SecurityConfig.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/swm_standard/phote/common/exception/ExpiredTokenException.kt
  src/main/kotlin/com/swm_standard/phote/common/resolver/memberId/MemberIdResolver.kt
  src/main/kotlin/com/swm_standard/phote/common/responsebody/EnumStatus.kt
  src/main/kotlin/com/swm_standard/phote/controller/TokenController.kt
  src/main/kotlin/com/swm_standard/phote/dto/AuthDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/RefreshToken.kt
  src/main/kotlin/com/swm_standard/phote/external/redis/RedisConfig.kt
  src/main/kotlin/com/swm_standard/phote/repository/RefreshTokenRepository.kt
  src/main/kotlin/com/swm_standard/phote/service/GoogleAuthService.kt
  src/main/kotlin/com/swm_standard/phote/service/KaKaoAuthService.kt
  src/main/kotlin/com/swm_standard/phote/service/TokenService.kt
Labels: ✨ Feature, 🫧 seyeon

#162 Fix: createQuestion 이미지 요청 타입 변경
  src/main/kotlin/com/swm_standard/phote/controller/QuestionController.kt
  src/main/kotlin/com/swm_standard/phote/dto/QuestionDtos.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: 🛠️ Fix, ☘️ surin

#165 Infra: docker compose file 세팅 & cd파일 수정
  .github/workflows/develop-cd.yml
  docker-compose-dev.yml
Labels: 🌏 Infra, ☘️ surin

#167 Fix: docker compose 환경변수 변경
  docker-compose-dev.yml
Labels: 🛠️ Fix, ☘️ surin

#170 Fix: env파일 경로 추가
  docker-compose-dev.yml
Labels: 🛠️ Fix, 🌏 Infra, ☘️ surin

#174 Fix: compose 파일 유저네임 추가
  docker-compose-dev.yml
Labels: 🛠️ Fix, 🌏 Infra, ☘️ surin

#172 Fix: Google Login 구현 변경
  src/main/kotlin/com/swm_standard/phote/controller/AuthController.kt
Labels: 🛠️ Fix, 🫧 seyeon

#176 Fix: kakao login 로직 변경
  src/main/kotlin/com/swm_standard/phote/controller/AuthController.kt
Labels: 🛠️ Fix, ☘️ surin

#177 Feat: receiveSharedWorkbook
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/Question.kt
  src/main/kotlin/com/swm_standard/phote/entity/Workbook.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
Labels: ✨ Feature, 🫧 seyeon

#179 Fix: 노출 불필요한 modifiedAt, createdAt 필터링하기
  src/main/kotlin/com/swm_standard/phote/dto/ExamDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/BaseTimeEntity.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
Labels: 🛠️ Fix, 🫧 seyeon

#181 Refactor: gradeExam 비동기 처리
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/entity/Answer.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
  src/test/kotlin/com/swm_standard/phote/entity/AnswerTest.kt
Labels: 🔨 Refactor, 🫧 seyeon

#183 Fix: createQuestion, transformQuestion requestBody 필드명 통일
  src/main/kotlin/com/swm_standard/phote/controller/AuthController.kt
  src/main/kotlin/com/swm_standard/phote/controller/QuestionController.kt
  src/main/kotlin/com/swm_standard/phote/controller/TokenController.kt
  src/main/kotlin/com/swm_standard/phote/controller/WorkbookController.kt
  src/main/kotlin/com/swm_standard/phote/dto/QuestionDtos.kt
  src/main/kotlin/com/swm_standard/phote/entity/RefreshToken.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
  src/test/kotlin/com/swm_standard/phote/entity/QuestionRepositoryTest.kt
  src/test/kotlin/com/swm_standard/phote/entity/QuestionTest.kt
Labels: 🛠️ Fix, 🔨 Refactor, 🫧 seyeon

#185 [Refactor] transformQuestion 비동기 처리
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: 🔨 Refactor, ☘️ surin

#187 Fix: dto 필드명 통일
  src/main/kotlin/com/swm_standard/phote/dto/ExamDtos.kt
  src/main/kotlin/com/swm_standard/phote/dto/QuestionDtos.kt
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/service/ExamService.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
Labels: 🛠️ Fix, ☘️ surin

#189 Fix: searchQuestionsToAdd에 questionId필드 추가
  src/main/kotlin/com/swm_standard/phote/dto/QuestionDtos.kt
  src/main/kotlin/com/swm_standard/phote/repository/QuestionCustomRepositoryImpl.kt
Labels: 🛠️ Fix, ☘️ surin

#191 Fix: kakao login redirect uri request로 요청 & POST 메소드로 변경
  src/main/kotlin/com/swm_standard/phote/controller/AuthController.kt
  src/main/kotlin/com/swm_standard/phote/dto/AuthDtos.kt
  src/main/kotlin/com/swm_standard/phote/service/KaKaoAuthService.kt
Labels: 🛠️ Fix, ☘️ surin

#193 Fix: Google Login redirect uri request로 요청
  src/main/kotlin/com/swm_standard/phote/controller/AuthController.kt
  src/main/kotlin/com/swm_standard/phote/service/GoogleAuthService.kt
Labels: 🛠️ Fix

#195 Fix: readQuestionsInWorkbook 의 options 형식 변경
  src/main/kotlin/com/swm_standard/phote/dto/WorkbookDtos.kt
  src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
Labels: 🛠️ Fix

#199 Refactor: transformQuestion 리팩토링
  build.gradle.kts
  src/main/kotlin/com/swm_standard/phote/controller/QuestionController.kt
  src/main/kotlin/com/swm_standard/phote/service/QuestionService.kt
Labels: ☘️ surin
